services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./blog-master:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    expose:
      - 9000
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=blog-master
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog-master
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./blog-master:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  mysql_data: